### ISSUE TITLE
Redirect url

### ISSUE THREAD

**Issue by salberts** [MelakuDemeke/telebirr-php#2]
Hi,

Thank you for this basic. We are just busy with a Telebirr integration. So this is very helpful.

I am curious to the point where it redirects to a payment url. I see a redirect IP with http. Is this the url where visitors get redirected to? Because non https and IP instead of domain name doesn't seem like a good solution.

Or do I miss something?

Many thanks for your good work!

**Comment by MelakuDemeke** [comment]
yes the payment URL is HTTP and in IP, this should be changed after you ask to go to production mode.
